yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

SYMBOL = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, db_index=True, verbose_name='User')
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Ваш пост',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True, db_index=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор')
    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Имя группы',
                              help_text='Группа, к которой относится пост')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:SYMBOL]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField(verbose_name='Текст комментария',
                            help_text='Напишите текст комментария')
    created = models.DateTimeField('date_created', auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.text[:SYMBOL]


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User, on_delete=models.CASCADE, unique=False,
                               related_name='following')

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='user_author')
        ]

    def __str__(self):
        return f'Пользователь:{self.user} подписался на {self.author}'

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {'group': 'Можете выбрать группу',
                      'text': 'Здесь напишите свой текст'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {'text': 'Напишите комментарий'}

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Follow, Group, Post, User
from .forms import PostForm, CommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user


NUMBER_OF_POST = 10
SYMBOLS_TEXT = 30


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, NUMBER_OF_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, NUMBER_OF_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
        'posts': posts,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    posts_number = posts.count()
    paginator = Paginator(posts, NUMBER_OF_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    follow = (request.user.is_authenticated and author != request.user
              and Follow.objects.filter(
                  author=author,
                  user=request.user).exists())
    context = {
        'author': author,
        'post_num': posts_number,
        'page_obj': page_obj,
        'following': follow,
    }
    template = 'posts/profile.html'
    return render(request, template, context)


def post_detail(request, post_id):
    posts = get_object_or_404(Post, pk=post_id)
    title = posts.text[:SYMBOLS_TEXT]
    posts_number = Post.objects.filter(author=posts.author).count()
    comments = posts.comments.all()
    form = CommentForm()
    author = posts.author
    context = {
        'post_num': posts_number,
        'post': posts,
        'title': title,
        'comments': comments,
        'author': author,
        'form': form,
    }
    template = 'posts/post_detail.html'
    return render(request, template, context)


@login_required
def post_create(request):
    user = get_user(request)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None)
    if form.is_valid():
        frm = form.save(commit=False)
        frm.author = user
        frm.save()
        return redirect(f'/profile/{user.username}/')
    form = PostForm(files=request.FILES or None)
    context = {
        'form': form,
        'is_edit': False,
    }
    template = 'posts/create_post.html'
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(f'/posts/{post_id}/')
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    template = 'posts/create_post.html'
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, NUMBER_OF_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    template = 'posts/follow.html'
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if (author != request.user
        and not Follow.objects.filter(user=request.user,
                                      author=author).exists()):
        Follow.objects.create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(Follow,
                      user=request.user,
                      author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}
  {% if is_edit %}
  Редактирование поста
  {% else %}
  Создание нового поста
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-body">
            <div class="card-header"> 
              {% if is_edit %}
                Редактировать запись
              {% else %}      
                Добавить запись
              {% endif %}
              </div>
                {% load user_filters %}
                  {% if form.errors %}
                    {% for field in form %}
                      {% for error in field.errors %}            
                        <div class="alert alert-danger">
                          {{ error|escape }}
                        </div>
                      {% endfor %}
                    {% endfor %}

                    {% for error in form.non_field_errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endif %}

                  {% if is_edit %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' form.instance.id %}">
                  {% else %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                  {% endif %} 


                  <form method='post' enctype="multipart/form-data">
                    {% csrf_token %}
                      <div class="form-group row my-3 p-3">
                        {{ form.image }}
                        <span class="helptext text-muted">Загрузите картинку</span>
                        <label for="id_text">Текст поста<span class="required text-danger" >*</span></label>
                        {{ form.text }}
                        <span class="helptext text-muted">Текст нового поста</span>
                      </div>
                      <div class="form-group row my-3 p-3">
                        <label for="id_group">Группа</label>
                        {{ form.group }}
                        <span class="helptext text-muted">Группа, к которой будет относиться пост</span>
                      </div>
                    <div class="d-flex justify-content-end">
                      <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Сохранить
                        {% else %}
                          Добавить
                        {% endif %}
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}

{% block title %} Избранное {% endblock %}

{% block content %}
{% load cache %}
  <div class="container">        
    <h1> Вам понравилось: </h1>
    {% include 'posts/includes/switcher.html' with follow=True %}
        {% cache 10 follow_index_page %}
        {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %}
                {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}    
    {% endcache %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block header %} Группа: {{ group.title }} {% endblock %}

{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container">
    <h1> {{ post.group }} </h1>
      <p> {{ group.description }} </p>
      {% for post in page_obj %}
        <article>
          <ul>
            <li> Группа: {{ post.group }} </li>
            <li> Автор: {{ post.author.get_full_name }} </li>
            <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
          </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
             <p>{{ post.text }}</p>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block header %} Последние обновления на сайте {% endblock %}

{% block content %}
{% load cache %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
      <h1>Последние обновления на сайте</h1>
      {% cache 20 index_page page_obj.number %}
        {% for post in page_obj %}
          {% include 'posts/includes/post_list.html' %}
          {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
          {% endif %}
          {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
      {% endcache %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %} 

{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
        {% endif %}            
        </li>
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ post_num }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            Все посты пользователя </a>
        </li>
      </ul>      
    </aside>      
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p> {{ post.text }} </p>
        <!-- эта кнопка видна только автору -->
        {% if post.author == request.user %} 
          <a class="btn btn-sm btn-secondary rounded" href="{% url 'posts:post_edit' post.pk %}" role="button">      
              Редактировать пост          
          </a>
        {% endif %}
      </article>
      {% include "includes/comments.html" %}
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %} 

{% block content %}
  <div class="container py-5">
    <h1> Все посты пользователя {{ author.get_full_name }} </h1>
      <h3> Всего постов: {{ post_num }} </h3>
      {% if user.is_authenticated %}
        {% if following %}
          <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
           Отписаться
          </a>
            {% else %}
              <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
              Подписаться
              </a>
        {% endif %}
      {% endif %}
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                  <a href="{% url 'posts:profile' post.author.username %}"> Все посты пользователя </a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail posts.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p> {{ post.text }} </p>
              <a href="{% url 'posts:post_detail' post.id %}"> Подробная информация </a>
              <p>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}"> Все записи группы </a>
            {% endif %}
           </article>
           {% if not forloop.last %}
           <hr>
           {% endif %}
        {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}